config/routes.rb
DbcOverflow::Application.routes.draw do
  root :to => "recipes#index"
  put "/recipes/:id/upvote" => "recipes#upvote", as: 'recipe_upvote'
  put "/recipes/:id/downvote" => "recipes#downvote", as: 'recipe_downvote'
  put "/recipes/:recipe_id/comments/:id/upvote" => "comments#upvote", as: "recipe_comment_upvote"
  put "/recipes/:recipe_id/comments/:id/downvote" => "comments#downvote", as: "recipe_comment_downvote"
  get '/recipes/search' => "recipes#new_search", as: "new_search"
  post '/recipes/search' => "recipes#search", as: "search"
  get '/recipes/random_list' => "recipes#random_list", as: "random"
  get '/signin' => 'users#signin_attempt', as: "signin"
  post '/logout' => 'users#logout', as: 'logout'

  resources :recipes do
    resource :comments
  end

  resources :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :votes
  validates :body, presence: true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :title, :content, :votes, :image_url
  has_many :comments
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true, uniqueness: true
end

app/models/user.rb
require "bcrypt"
class User < ActiveRecord::Base
	# validates :username, presence: true, uniqueness: true
	validates :password_hash, presence: true
	attr_accessible :username, :password_hash
	include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end
  # Remember to create a migration!

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.new(body: params[:comment][:body])
    @recipe.comments << @comment
    respond_to do |format|
      format.json {render json: {body: @comment.body, votes: @comment.votes}}
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      redirect_to recipes_path
    else
      render :edit
    end
  end

  def destroy
    Recipe.delete(params[:id])
    redirect_to recipes_path
  end

  def upvote
    recipe = Recipe.find(params[:recipe_id])
    comment = Comment.find(params[:id])
    comment.votes += 1
    comment.save
    respond_to do |format|
      format.json {render json: {votes: comment.votes}}
    end
  end

  def downvote
    recipe = Recipe.find(params[:recipe_id])
    comment = Comment.find(params[:id])
    comment.votes -= 1
    comment.save
    respond_to do |format|
      format.json {render json: {votes: comment.votes}}
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @comments = @recipe.comments
    @comment = Comment.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    search_term = params[:recipe][:title]
    response = YummlyAdapter.search(search_term)
    puts response
    response["matches"].empty? ? photo_url = "/images/rails.png" : photo_url = response["matches"][0]["imageUrlsBySize"]["90"]
    @recipe = Recipe.new(title: params[:recipe][:title], content: params[:recipe][:content], image_url: photo_url )
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      redirect_to recipes_path
    else
      render :edit
    end
  end

  def destroy
    Recipe.delete(params[:id])
    redirect_to recipes_path
  end

  def upvote
    recipe = Recipe.find(params[:id])
    recipe.votes += 1
    recipe.save
    respond_to do |format|
      format.json {render json: {votes: recipe.votes}}
    end
  end

  def downvote
    recipe = Recipe.find(params[:id])
    recipe.votes -= 1
    recipe.save
    respond_to do |format|
      format.json {render json: {votes: recipe.votes}}
    end
  end

  def random_list
    @recipes = []
    results = HTTParty.get("http://frozen-ravine-7501.herokuapp.com/api/v1/22da81825c25c4a380dd/recipes")
    results.parsed_response.each do |recipe|
      @recipes << Recipe.create(title: recipe['title'], content: recipe["content"])
    end
  end

  def new_search
    @recipe = Recipe.new
  end

  def search
   puts RecipesAdapter.search(params[:recipe][:content])
  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def show
	end

	def create
		p params
		@user = User.new(username: params[:user][:username])
		@user.password = params[:user][:password_hash]
		@user.save
		session[:id] = @user.id
		if session[:id]
			redirect_to recipes_path
		else
			redirect_to new_user_path
		end
	end

	def update
	end

	def signin_attempt
		@user = User.new
		render :signin
	end

	def signin
		@user = User.find(params[:username])
		if params[:password_hash] == @user.password
			session[:id] = @user.id
			redirect_to recipes_path
		else
			render :signin
		end
	end

	def logout
		session[:id] = nil
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
require 'uri'
module ApplicationHelper
  def self.base_url
    "http://api.yummly.com/v1/api/recipes?_app_id=08bc60b4&_app_key=ea1853f224bd17d6ee0b20e994147c9d&q="
  end

  def self.target_url(search_term)
    actual_term = search_term.gsub(" ", "+")
    URI.parse(URI.encode(ApplicationHelper.base_url + actual_term + "&requirePictures=true"))
  end
end


class YummlyAdapter
  def self.search(target)
    HTTParty.get(ApplicationHelper.target_url(target))
  end
end


class RecipesAdapter
  def self.serialize_input(terms)
    result = terms.downcase.gsub(" ", "+")
    result
  end

  def self.base_url(terms)
    URI.parse(URI.encode('http://example.com:3000/api/v1/aa02223a4295fa18b531/recipes/search/' + RecipesAdapter.serialize_input(terms)))
  end

  def self.search(terms)
    HTTParty.get(RecipesAdapter.base_url(terms))
  end
end

app/views/comments/_comments.html.erb
<% if !@comments.empty? %>
	<h3> Comments: </h3>
<% end %>

<% @comments.sort_by{|x| x.votes}.reverse.each do |comment| %>
  <article id="comment_template" class="border">
    <h5 class="vote_count"><%= comment.votes %></h5>
    <%= link_to recipe_comment_upvote_path(@recipe, comment), method: 'put', remote: true, class: "upvote_button" do %>
      <i class="fa fa-arrow-circle-o-up"></i>
    <% end %>
    <%= link_to recipe_comment_downvote_path(@recipe,comment), method: 'put', remote: true, class: "downvote_button" do %>
      <i class="fa fa-arrow-circle-o-down"></i>
    <% end %>
    <p> <%= comment.body %> </p>
  </article>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@recipe, @comment], remote: true,html: { class: "comment_button"}) do |r| %>
  Comment Body: <%= r.text_field :body %><br/>
  <%= r.submit %>
<% end %>

app/views/comments/new.html.erb
<%= render 'comments/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<header class="full-width dark-grey">
  <h2 class="align-middle">Recipe Overflow</h2>
  <h4 class="absolute-right align-middle"> <%= link_to "New Recipe", new_recipe_path %> </h4>
	  <ul class="absolute-right" style="margin-right:150px;list-style-type:none;">
	  	<% if !session[:id] %>
		  	<li> <%= link_to "Create Account", new_user_path %> </li>
		  	<li> <%= link_to "Sign in ", signin_path %> </li>
		  	<li> <%= link_to "Random Recipe list", random_path%> </li>
		  	<li> <%= link_to "Search", new_search_path%> </li>
		  <% else %>
		  	<li> <%= link_to "Logout", logout_path, method: 'post' %> </li>
		  <% end %>
	 	</ul>

</header>
<%= yield %>


<p id = "markdown_template" style='display:none;'></p>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |r| %>
  Title: <%= r.text_field :title %><br/>
  Content: <%= r.text_area :content %><br/>
  <%= r.submit %>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/index.html.erb
<h2 class="ta-center">All Recipes</h2>
<div class="width70 center ta-center">
  <% @recipes.each do |recipe| %>
    <article id = <%="#{recipe.id}"%> >
      <h3><%= link_to recipe.title, recipe_path(recipe) %></h3>

      <div class="mt-45">
        <%= link_to recipe_upvote_path(recipe), method: 'put', remote: true, class: "upvote_button" do %>
          <i class="fa fa-arrow-circle-o-up"></i>
        <% end %>
        <%= link_to recipe_downvote_path(recipe), method: 'put', remote: true, class: "downvote_button" do %>
          <i class="fa fa-arrow-circle-o-down"></i>
        <% end %>
        <p class="vote_count"><%= recipe.votes %> </p>
      </div>
      <ul class="style-none">
        <li> <%= link_to "Edit", edit_recipe_path(recipe) %></li>
        <li> <%= link_to "Delete", recipe_path(recipe), method: :delete %></li>
      </ul>
    </article>
  <% end %>
</div>

app/views/recipes/new.html.erb
<%= render 'form' %>

<div class="preview_container">
</div>

app/views/recipes/new_search.html.erb
<%= form_for(@recipe, url: search_path, method: 'post') do |r| %>
  Search: <%= r.text_field :content %><br/>
  
  <%= r.submit %>
<% end %>

app/views/recipes/random_list.html.erb
<% @recipes.each do |r| %>
	<h2><%= r.title %> </h2>
	<p><%= r.content %></p>
<% end %>

app/views/recipes/show.html.erb
<div class="width70 center ta-center">
  <article>
    <h3 class="ta-left"><%= @recipe.title %></h3>
    <img src=<%="#{@recipe.image_url}" %>>
    <hr/>
    <div class="mt-45 pull-left">
      <%= link_to recipe_upvote_path(@recipe), remote: true, method: 'put', class: "upvote_button" do %>
        <i class="fa fa-arrow-circle-o-up"></i>
      <% end %>
      <%= link_to recipe_downvote_path(@recipe), remote: true, method: 'put', class: "downvote_button" do %>
        <i class="fa fa-arrow-circle-o-down"></i>
      <% end %>
      <p class="vote_count"><%= @recipe.votes %> </p>
    </div>
    <div id="comment_feed" class="inline-block width70">
      <p class="inline-block ta-left"><%= @recipe.content %></p>
    </div>
    <div class="comment_feed">
      <%=  render 'comments/comments' %>
    </div>
    <%= render 'comments/form'%>
  </article>
</div>

app/views/users/new.html.erb
<%= form_for(@user) do |u| %>
	Username: <%= u.text_field :username %><br/>
	Password: <%= u.text_field :password_hash %><br/>
  <%= u.submit %>
<% end %>

app/views/users/signin.html.erb
<%= form_for(@user) do |u| %>
	Username: <%= u.text_field :username %><br/>
	Password: <%= u.text_field :password_hash %><br/>
  <%= u.submit %>
<% end %>